// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: server.proto

package blockrazorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendBinaryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BinaryTransaction []byte                 `protobuf:"bytes,1,opt,name=binaryTransaction,proto3" json:"binaryTransaction,omitempty"`
	Mode              string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	SafeWindow        int32                  `protobuf:"varint,3,opt,name=safeWindow,proto3" json:"safeWindow,omitempty"`
	RevertProtection  bool                   `protobuf:"varint,4,opt,name=revertProtection,proto3" json:"revertProtection,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendBinaryRequest) Reset() {
	*x = SendBinaryRequest{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBinaryRequest) ProtoMessage() {}

func (x *SendBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBinaryRequest.ProtoReflect.Descriptor instead.
func (*SendBinaryRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *SendBinaryRequest) GetBinaryTransaction() []byte {
	if x != nil {
		return x.BinaryTransaction
	}
	return nil
}

func (x *SendBinaryRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SendBinaryRequest) GetSafeWindow() int32 {
	if x != nil {
		return x.SafeWindow
	}
	return 0
}

func (x *SendBinaryRequest) GetRevertProtection() bool {
	if x != nil {
		return x.RevertProtection
	}
	return false
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\bserverpb\"\xa1\x01\n" +
	"\x11SendBinaryRequest\x12,\n" +
	"\x11binaryTransaction\x18\x01 \x01(\fR\x11binaryTransaction\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1e\n" +
	"\n" +
	"safeWindow\x18\x03 \x01(\x05R\n" +
	"safeWindow\x12*\n" +
	"\x10revertProtection\x18\x04 \x01(\bR\x10revertProtection\",\n" +
	"\fSendResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature2V\n" +
	"\x06Server\x12L\n" +
	"\x15SendBinaryTransaction\x12\x1b.serverpb.SendBinaryRequest\x1a\x16.serverpb.SendResponseBAZ?github.com/0xfnzero/sol-trade-sdk-golang/pkg/swqos/blockrazorpbb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_proto_goTypes = []any{
	(*SendBinaryRequest)(nil), // 0: serverpb.SendBinaryRequest
	(*SendResponse)(nil),      // 1: serverpb.SendResponse
}
var file_server_proto_depIdxs = []int32{
	0, // 0: serverpb.Server.SendBinaryTransaction:input_type -> serverpb.SendBinaryRequest
	1, // 1: serverpb.Server.SendBinaryTransaction:output_type -> serverpb.SendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
